name: "Scan for vulnerabilities"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  vulnerability:
    name: Nightly Vulnerability Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - master
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Check
        id: check
        run: mvn -B -U -DskipTests -DskipChecks -Ddependency-check.skip=false package dependency-check:check
